cloud:
  aws:
    credentials:
      access-key: AKIAUO3EUIXZ4WSGIPGP
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: huy-property-images
